//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchetAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int IDCar { get; set; }
        public string GarNumber { get; set; }
        public string Model { get; set; }
        public string NumberCar { get; set; }
        public Nullable<int> IDDriver { get; set; }
        public Nullable<int> IDFil { get; set; }
        public Nullable<System.DateTime> DatePost { get; set; }
        public string Trailer { get; set; }
        public Nullable<int> IDTypeCar { get; set; }
        public Nullable<int> IDTypeMotor { get; set; }
        public Nullable<int> IDTypeCarBody { get; set; }
        public Nullable<decimal> VMotor { get; set; }
        public Nullable<System.DateTime> DateVipusk { get; set; }
        public Nullable<decimal> Gruzopod { get; set; }
        public Nullable<int> Whel { get; set; }
        public Nullable<int> Spare { get; set; }
        public Nullable<decimal> Odometer { get; set; }
        public Nullable<decimal> MotoHour { get; set; }
        public Nullable<int> IDFuel { get; set; }
        public Nullable<decimal> VTank { get; set; }
        public Nullable<decimal> BalanceTank { get; set; }
        public Nullable<decimal> LinNorma { get; set; }
        public Nullable<decimal> WithTrailer { get; set; }
        public Nullable<decimal> Na100TonnKm { get; set; }
        public Nullable<decimal> Mechanizm { get; set; }
        public Nullable<decimal> Gorod100 { get; set; }
        public Nullable<decimal> Gorod300 { get; set; }
        public Nullable<decimal> Gorod1000 { get; set; }
        public Nullable<decimal> WithStop { get; set; }
        public Nullable<decimal> Slowly { get; set; }
        public Nullable<decimal> Offroad { get; set; }
        public Nullable<decimal> Highway { get; set; }
        public Nullable<decimal> Amortiz { get; set; }
        public Nullable<decimal> Conditioning { get; set; }
        public Nullable<decimal> Heater { get; set; }
        public Nullable<decimal> AddBlue { get; set; }
        public Nullable<decimal> Career { get; set; }
        public Nullable<System.DateTime> Tehosmotr { get; set; }
        public Nullable<int> IDYear { get; set; }
        public Nullable<decimal> Generator { get; set; }
    
        public virtual Filial Filial { get; set; }
        public virtual Fuel Fuel { get; set; }
        public virtual TypeCar TypeCar { get; set; }
        public virtual TypeCarBody TypeCarBody { get; set; }
        public virtual TypeMotor TypeMotor { get; set; }
        public virtual Voditel Voditel { get; set; }
        public virtual Year Year { get; set; }
    }
}
