//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchetAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Passport()
        {
            this.Voditel = new HashSet<Voditel>();
        }
    
        public int IDPas { get; set; }
        public string IDNumber { get; set; }
        public string Seria { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> DatRoj { get; set; }
        public string Propis { get; set; }
        public string Vidan { get; set; }
        public Nullable<System.DateTime> Srok { get; set; }
        public string Priznak1 { get; set; }
        public string Priznak2 { get; set; }
        public string Priznak3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voditel> Voditel { get; set; }
    }
}
