//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchetAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Podrazd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Podrazd()
        {
            this.Voditel = new HashSet<Voditel>();
        }
    
        public int IDPodr { get; set; }
        public string Podrazd1 { get; set; }
        public Nullable<int> IDFilial { get; set; }
        public string Priznak { get; set; }
    
        public virtual Filial Filial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voditel> Voditel { get; set; }
    }
}
