//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchetAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voditel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voditel()
        {
            this.Cars = new HashSet<Cars>();
        }
    
        public int IDVod { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Address { get; set; }
        public string PhoneGor { get; set; }
        public string PhoneMob { get; set; }
        public Nullable<int> IDFil { get; set; }
        public Nullable<int> IDPass { get; set; }
        public Nullable<int> IDVodUd { get; set; }
        public Nullable<int> IDVoen { get; set; }
        public Nullable<System.DateTime> MedKomis { get; set; }
        public string Priznak1 { get; set; }
        public string Priznak2 { get; set; }
        public string Priznak3 { get; set; }
        public string TabNumber { get; set; }
        public Nullable<int> IDDolj { get; set; }
        public Nullable<int> IDPodr { get; set; }
        public Nullable<int> Klass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cars> Cars { get; set; }
        public virtual Doljnost Doljnost { get; set; }
        public virtual Filial Filial { get; set; }
        public virtual Passport Passport { get; set; }
        public virtual Podrazd Podrazd { get; set; }
        public virtual VodUd VodUd { get; set; }
        public virtual VoenBilet VoenBilet { get; set; }
    }
}
