//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchetAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VodUd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VodUd()
        {
            this.Voditel = new HashSet<Voditel>();
        }
    
        public int IDVUd { get; set; }
        public string Number { get; set; }
        public string Cateroria { get; set; }
        public Nullable<System.DateTime> SrokD { get; set; }
        public string Priznak1 { get; set; }
        public string Priznak2 { get; set; }
        public string Priznak3 { get; set; }
        public string AM { get; set; }
        public string A { get; set; }
        public string A1 { get; set; }
        public string B { get; set; }
        public string C { get; set; }
        public string D { get; set; }
        public string BE { get; set; }
        public string CE { get; set; }
        public string DE { get; set; }
        public string F { get; set; }
        public string I { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voditel> Voditel { get; set; }
    }
}
