//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchetAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoenBilet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VoenBilet()
        {
            this.Voditel = new HashSet<Voditel>();
        }
    
        public int IDVoen { get; set; }
        public string Number { get; set; }
        public string Zvanie { get; set; }
        public string Priznak1 { get; set; }
        public string Priznak2 { get; set; }
        public string Priznak3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voditel> Voditel { get; set; }
    }
}
